### PR TITLE
same PR for the xenial branch

### PR DESCRIPTION
**Pull request by balcy**
in https://github.com/ubports/build-tools/blob/master/build-source.sh there is 
DIST="vivid xenial artful bionic", so the same source code has to build for vivid and xenial.

I can do this via preprocessor directives (Qt Version), but since vivid will be obsolete soon, I think it is unneccesary...
```
if echo $DIST | grep -w $GIT_BRANCH > /dev/null; then
        echo "This is on a release branch, overriding dist to $GIT_BRANCH"
        export DIST_OVERRIDE=$GIT_BRANCH
fi
```
I hope that by that directive the xenial branch CI will only build for xenial

### CODE REVIEW

**Comment by balcy** [comment]
can we try how the merge behaves here ?

**Comment by balcy** [comment]
@hummlbach to avoid the dependency problems with installing libreoffice, I have created a chroot container and ran `clickable --container-mode` inside it. 
Then I did the following:

- change the line in the Click.cmake file to ` #INSTALL(DIRECTORY /usr/lib/libreoffice/ DESTINATION ${DATA_DIR}lib/${ARCH_TRIPLET}/libreoffice )`
- this will produce a click package of about 80 MB that can be installed
- via the logs it then complained about still missing libraries
- I added those manually to the `/opt/click.ubuntu.com/.click/uers/phablet/com.ubuntu.docviewer/lib/arm-linux-gnueabihf` (or its subfolder libreoffice/program)
- the bad news is : even if the log now states "Document loaded successfully", the docviewer crashes on the phone

**Comment by balcy** [comment]
I've added some sceenshots here: https://forums.ubports.com/topic/1510/build-docviewer-with-libreoffice-support-for-xenial

**Comment by balcy** [comment]
@Flohack74 @NeoTheThird  can we try the merge then ? I mean still better to have a docviewer without libreoffice support (for now) than no docviewer at all ?

**Comment by Flohack74** [comment]
Yes but the last CI build failed, and though you pushed changes onto this PR it did not try to rebuild, which is very strange... We need a good deb build in order to then go to the click builder. I need to take a look what's wrong.

**Comment by Flohack74** [comment]
Ok found it, there was no Jenkinsfile in xenial. Please update your branch from our branch and commit to the PR.

**Comment by Flohack74** [comment]
No need to close :) - just continue to commit on top of it

**Comment by Flohack74** [comment]
DONT CLOSE IT :) all the time

**Comment by balcy** [comment]
I was just puzzled because my PR already contained the Jenkinsfile ...
and I am not used to the heat and git : ]

**Comment by balcy** [comment]
will check out the problems tomorrow / the next days

**Comment by Flohack74** [comment]
Ok please rebase once more I changed hopefully the changelog in a good way ;)

**Comment by Flohack74** [comment]
I merged this now so that we got a clean state somehow, and start over with PRs if necessary. This got too long already.

**Comment by nfsprodriver** [comment]
Shouldn't we move over to clickable? For me clickable works with docviewer :)

**Comment by Flohack74** [comment]
Yes but the deb build is easier for me to automate. In the end it will be a click. So now lets focus on how to get LibreOffice going...

On the other hand, can you prepare a click for the openstore, people can at least use if for PDFs then.

**Pull request merged**
